### ISSUE TITLE
Criar branchs baseado no Gitflow

### ISSUE THREAD

**Issue by cesimarxavier** [awescolar/geostatics#1]
Criar os seguintes _branchs_ (para @Milena-Xavier)

- _develop_ (criar)
- _release_ (criar)
- _hotfix_ (criar)
- _main_ (manter)

**Comment by Milena-Xavier** [comment]
Os branchs principais foram criados utilizando o fluxo Git Flow. De modo que o branch main é direcionado aos códigos já versionados, e o develop será a base de todo o fluxo de trabalho. Ademais, as pastas do projeto foram commitadas e organizadas conforme o solicitado.

**Comment by cesimarxavier** [comment]
@Milena-Xavier o _branch main_ deverá ser atualizado apenas quando a versão estiver **estável** e **liberada**. Por enquanto não temos uma versão com essas características do nosso **app**, o que implica que não podemos fazer isso agora.

Outro ponto, isso vale para todos (@Jady-Lima, @YasminMarquess), não devemos nunca enviar um _commit_ direto para o _main_. Sempre devemos enviar para o _develop_, caso esteja em desenvolvimento e esteja estável.
