### ISSUE TITLE
Fazer commit do arquivo SCSS do Bootstrap

### ISSUE THREAD

**Issue by cesimarxavier** [awescolar/geostatics#3]
@Jady-Lima 

após a criação da estrutura de pastas, você deverá fazer o _commit_ dos arquivos do Bootstrap na branch _develop_ e pasta _/view/scss/_

**Comment by Milena-Xavier** [comment]
Os arquivos para o uso do Bootstraps foram commitados para a pasta _/view/scss/_ e estão disponíveis apenas na branch _develop._
